#!/bin/bash

# Define workspace names
workspace_names=("1" "2" "3" "4" "5")

# Get the primary monitor (assuming eDP-1 is primary, adjust as needed)
primary_monitor=$(xrandr --query | awk '/ connected primary/ {print $1}')

# Counter to assign workspaces to monitors
counter=0

# Iterate through all connected monitors
for monitor in $(xrandr --query | awk '/ connected/ {print $1}'); do
    # Assign workspaces to the current monitor
    bspc monitor "$monitor" -d "${workspace_names[@]}"

    # If the monitor is not the primary, position it to the right of the primary
    if [ "$monitor" != "$primary_monitor" ]; then
        xrandr --output "$monitor" --auto --right-of "$primary_monitor"
        primary_monitor="$monitor" # Set the current monitor as the new primary for the next iteration
    fi

    # Increment counter to move to the next set of workspaces if more monitors are connected
    counter=$((counter + 1))
done

# Configure BSPWM settings
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'

# Terminate already running instances
for process in "sxhkd" "polybar" "dunst"; do
    if pgrep -f "$process"; then
        pkill -f "$process" >/dev/null
    fi
done

# Set wallpaper
feh --bg-fill $HOME/Pictures/Wallpapers/archkali.png &

# Launch sxhkd
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# Launch Picom
picom --config $HOME/.config/picom/picom.conf &

# Launch dunst
dunst -config $HOME/.config/dunst/dunstrc &

# Launch Polybar
$HOME/.config/polybar/launch.sh &

# Launch numlockx
numlockx &
