#!/bin/bash

# Configure BSPWM settings
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'

# Terminate already running instances
for process in "sxhkd" "polybar" "dunst"; do
    if pgrep -f "$process"; then
        pkill -f "$process" >/dev/null
    fi
done

# Launch applications
feh --bg-fill $HOME/Pictures/Wallpapers/archkali.png &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
picom --config $HOME/.config/picom/picom.conf &
dunst -config $HOME/.config/dunst/dunstrc &
numlockx &
1password --silent &

# Launch scripts
$HOME/.config/bspwm/scripts/monitor_config.sh &
$HOME/.config/polybar/launch.sh &
