return {
  ensure_installed = {
    "ansiblels",
    "astro",
    "bashls",
    "cssls",
    "docker_compose_language_service",
    "dockerls",
    "emmet_ls",
    "eslint",
    "graphql",
    -- "groovyls",
    "helm_ls",
    "html",
    "jsonls",
    "lua_ls",
    "marksman",
    "nextls",
    -- "nginx_language_server",
    "prismals",
    "pyright",
    "sqlls",
    "snyk_ls",
    "tailwindcss",
    "terraformls",
    "tflint",
    "ts_ls",
    "unocss",
    "vtsls",
    "yamlls",
  },
  -- Automatically enable installed LSP servers
  -- Set to `false` to disable auto-enable globally
  -- or pass a table to include/exclude specific servers
  automatic_enable = true,
}
